LibaryApp/Models/ErrorViewModel.cs
namespace LibaryApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LibaryApp/Controllers/BookController.cs
using FluentValidation.Results;
using Libary.Business.Abstract;
using Libary.Business.ValidationRules;
using LibaryApp.Core.Entities;
using LibaryApp.Core.Result;
using LibaryApp.Entity.Dtos.BookDtos;
using LibaryApp.Entity.Dtos.BorrowerBookDtos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace LibaryApp.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookService _bookService;

        public BookController(IBookService bookService)
        {
            _bookService = bookService;
        }
   
        public IActionResult GetAll()
        {
            var result = _bookService.GetBooks();
            return View(result.Data);
        }
  
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        } 
        [HttpPost]
        public IActionResult Add(AddBookDto dto, IFormFile image) //Kitap ekleme controller'ı
        {
            var result = _bookService.AddBook(dto, image);
            if (result.Data ==null)
            {
                return View(dto);
            }
            return RedirectToAction("GetAll");
        } 


        [HttpGet]
        public IActionResult GetBookById(int id)
        {
            var result = _bookService.GetBookById(id);
            return View("GetBookById", result.Data);
        } //Ödünç verme işleminde otomatik olarak BookId'yi otomatik almamı sağlayan controllerım

        public IActionResult GetActiveBooks()
        {
            var result = _bookService.GetActiveBooks();
            return View(result.Data);
        } //Kütüphanede aktif olan kitapları getiren Controller
    }
}

LibaryApp/Controllers/BorrowerBooksController.cs
using Libary.Business.Abstract;
using LibaryApp.Entity.Dtos.BorrowerBookDtos;
using Microsoft.AspNetCore.Mvc;

namespace LibaryApp.Controllers
{
    public class BorrowerBooksController : Controller
    {
        private readonly IBorrowerBooksService _borrowerBooksService;

        public BorrowerBooksController(IBorrowerBooksService borrowerBooksService)
        {
            _borrowerBooksService = borrowerBooksService;
        }
     
        [HttpGet]
        public IActionResult GetBorrowerBooksList() //Ödünç verilen kitaplar listesi controller'ı
        {
            var result=_borrowerBooksService.GetBorrowerBooksList();
            return View(result.Data);
        }

        [HttpGet]
        public IActionResult AddBorrowerBook(int bookId)
        {
            AddBorrowerBooksDto dt = new()
            {
                BookId = bookId
            };
            return View(dt);
        }
        [HttpPost]
        public IActionResult AddBorrowerBook(AddBorrowerBooksDto addBorrowerBooksDto)
        {
            //Bugünün tarihinden daha küçük bir Geri Getirme Tarihi girilmemesi için yaptığım kontrol
            if (addBorrowerBooksDto.ReturnDate < DateTime.Now.Date)
            {
                ModelState.AddModelError("ReturnDate", "Geri getirme tarihi bugünden küçük olamaz.");
                return View(addBorrowerBooksDto);
            }
            var result = _borrowerBooksService.AddBorrowerBook(addBorrowerBooksDto);
            return RedirectToAction("GetBorrowerBooksList");
        }

    }
}

LibaryApp/Controllers/HomeController.cs
using LibaryApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LibaryApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LibaryApp/Views/Book/Add.cshtml
 @model LibaryApp.Entity.Dtos.BookDtos.AddBookDto
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_LayoutTemplate.cshtml";
}
<hr />

<div class="giris">
    <div class="form">
         <form class="giris-from" method="post" enctype="multipart/form-data">
            <b>Kitap Ekleme Sayfası</b>

            <hr />
            <br />
        <div class="">
            <input type="text" name="BookName" placeholder="Kitap Adı" />
             <label type="text" style="color:red">  @Html.ValidationMessageFor(x=>x.BookName) </label>
              <br />
            <input type="text" name="Author" placeholder="Yazar" />
            <label type="text" style="color:red">  @Html.ValidationMessageFor(x => x.Author) </label>
            <br />
            <input type="file" class="form-control-file" name="Image" placeholder="Kitap Resmi" />
             <label type="text" style="color:red">  @Html.ValidationMessageFor(x => x.Image) </label>

        </div>
        <div style="margin-top:15px">
            <button type="submit" class="btn btn-info">Kitap Ekle</button>
        </div>
    </form>
    </div>
   
</div>
 
<style>
  
    .giris {
        width: 360px;
        padding: 1% 0 0;
        margin-left: 330px;
        margin-top: -26px;
    }
      .form {
        position: relative;
        z-index: 1;
        background: #FFFFFF;
        max-width: 360px;
        margin: 0 auto 100px;
        padding: 45px;
        text-align: center;
        box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
    }
    .form input {
            font-family: "Roboto", sans-serif;
            outline: 0;
            background: #f2f2f2;
            width: 100%;
            border: 0;
            margin: 0 0 15px;
            padding: 15px;
            box-sizing: border-box;
            font-size: 14px;
        }

         .form button {
            font-family: "Roboto", sans-serif;
            text-transform: uppercase;
            outline: 0;
            background: royalblue;
            width: 100%;
            border: 0;
            padding: 15px;
            color: #FFFFFF;
            font-size: 14px;
            -webkit-transition: all 0.3 ease;
            transition: all 0.3 ease;
            cursor: pointer;
        }
              .form button:hover, .form button:active, .form button:focus {
                background: slateblue
            }
             .container {
        position: relative;
        z-index: 1;
        max-width: 300px;
        margin: 0 auto;

LibaryApp/Views/Book/GetActiveBooks.cshtml
@using LibaryApp.Entity.Concrete
@model List<Book>
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_LayoutTemplate.cshtml";
}
<div class="container-fluid">
    <!-- DataTales-->
    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <b>Kütüphanedeki Kitaplar</b>

                    <hr />
                    <thead>

                        <tr>

                            <th class="book-info"></th>
                            <th class="book-info">Resim</th>
                            <th class="book-info">Kitap</th>
                            <th class="book-info">Yazar</th>
                            <th class="book-info">Durum</th>
                            <th class="book-info">Kaydedilme Tarihi</th>
                            <th class="book-info"></th>
                    
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var books in Model)
                        {
                            <tr>
                                <td style="text-align: center; vertical-align: middle">@books.Id</td>
                                <td>
                                    <img src="~/images/@books.Image" alt=" Kitap Resmi" style="width: 100px; height: 100px" ; class="img-thumbnail" />
                                </td>
                                <td style="text-align: center; vertical-align: middle;">@books.BookName</td>
                                <td style="text-align: center; vertical-align: middle">@books.Author</td>
                                <td style="text-align: center; vertical-align: middle">Kütüphanede</td>
                                <td style="text-align: center; vertical-align: middle">@books.CreatedDate</td>
                                <td>
                                           
                                    <div class="book-info">
                                            @using (Html.BeginForm("AddBorrowerBook", "BorrowerBooks", FormMethod.Get))
                                            {
                                                @Html.Hidden("bookId", books.Id)
                                            <button class="btn btn-primary borrow-btn">Ödünç Ver</button>
                                            }
                                </td>
                            </tr>

                        }


                    </tbody>
                </table>



                <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
                <script src=" https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
                <script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap4.min.js"></script>
                <script src=" https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css"></script>

                <script src="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap4.min.css"></script>
                <script type="text/javascript">
                    var js = jQuery.noConflict(true);
                    js(document).ready(function () {
                        js('#dataTable').DataTable({
                            language: {
                                url: '//cdn.datatables.net/plug-ins/1.13.6/i18n/tr.json',
                            },

                        });
                    });
                </script>

            </div>
        </div>
    </div>


</div>

<style>

    th {
        vertical-align: middle;
        text-align: center;
    }

    .disabled-button {
        pointer-events: none; /* Butona tıklama olaylarını devre dışı bırakır */
        opacity: 0.6; /* Butonun opaklığını azaltır, tıklanamaz gibi görünmesini sağlar */
    }

    .borrow-btn {
        margin-top: 30px;
        margin-left: 5%;
        margin-right: 5%;
    }

    /* DataTables sayfalama düğmelerini düzenle */
    .dataTables_wrapper .dataTables_paginate {
        float: left;
        margin-top: 10px;
    }

    /* Arama kutusunu düzenle */
    .dataTables_wrapper .dataTables_filter {
        float: right;
        margin-top: 10px;
        background-color: #FFFFFF;
        margin: 10px, 10px, 10px, 10px;
    }
</style>

LibaryApp/Views/Book/GetAll.cshtml
@using LibaryApp.Entity.Dtos.BookDtos
@model List<ListBookDto>
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_LayoutTemplate.cshtml";
}
<div class="container-fluid">
    <!-- DataTales-->
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="table-responsive">
                <b>Kütüphanedeki ve Dışarıdaki Kitaplar Listesi</b>
                <a href="/Book/Add/" class="btn btn-primary" style="float: right;"> Kitap Ekle</a>

                <hr />

                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>

                            <tr>

                                <th class="book-info"></th>
                                <th class="book-info">Resim</th>
                                <th class="book-info">Kitap</th>
                                <th class="book-info">Yazar</th>
                                <th class="book-info">Durum</th>
                                <th class="book-info"></th>
                                <th class="book-info">Alanın İsmi</th>
                                <th class="book-info">Getireceği Tarih</th>
                            </tr>
                        </thead>
                        <tbody>
                          
                                @foreach (var books in Model)
                                 
                                {
                                <tr>
                                <td style="text-align: center; vertical-align: middle">@books.Number</td>
                                    <td>
                                        <img src="~/images/@books.Image" alt=" Kitap Resmi" style="width: 100px; height: 100px" ; class="img-thumbnail" />
                                    </td>
                                <td style="text-align: center; vertical-align: middle;">@books.BookName</td>
                                <td style="text-align: center; vertical-align: middle">@books.Author</td>
                                <td style="text-align: center; vertical-align: middle">@books.InLibary</td>
                                    <td>
                                        @if (books.InLibary == "Dışarıda")
                                        {
                                            <div class="book-info">
                                                @using (Html.BeginForm("AddBorrowerBook", "BorrowerBooks", FormMethod.Get))
                                                {
                                                    @Html.Hidden("bookId", books.Id)
                                                <button class="btn btn-primary disabled-button borrow-btn" type="button">Ödünç Ver</button>
                                                }
                                            </div>
                                    <td style="text-align: center; vertical-align: middle">@books.BorrowersName</td>
                                    <td style="text-align: center; vertical-align: middle">@books.ReturnDate</td>
                                        }
                                        else
                                        {
                                        <div class="book-info">
                                                @using (Html.BeginForm("AddBorrowerBook", "BorrowerBooks", FormMethod.Get))
                                                {
                                                    @Html.Hidden("bookId", books.Id)
                                            <button class="btn btn-primary borrow-btn">Ödünç Ver</button>
                                                }
                                        </div>

                                    <td style="text-align: center; vertical-align: middle">#</td>
                                    <td style="text-align: center; vertical-align: middle">#</td>
                                        }
                                    </td>
                            </tr>

                                }

                          
                        </tbody>
                    </table>
           


                <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
                <script src=" https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
                <script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap4.min.js"></script>
                <script src=" https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css"></script>
               
                <script src="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap4.min.css"></script>
                    <script type="text/javascript">
                        var js = jQuery.noConflict(true);
                        js(document).ready(function () {
                            js('#dataTable').DataTable({
                                language: {
                                    url: '//cdn.datatables.net/plug-ins/1.13.6/i18n/tr.json',
                                },
                                
                            });
                        });
                    </script>

                </div>
            </div>
        </div>


</div>

<style>

     th{
        vertical-align: middle;
        text-align: center;
     }
        .disabled-button {
        pointer-events: none; /* Butona tıklama olaylarını devre dışı bırakır */
        opacity: 0.6; /* Butonun opaklığını azaltır, tıklanamaz gibi görünmesini sağlar */ 
        }

    .borrow-btn {
        margin-top: 30px;
        margin-left: 5%;
        margin-right: 5%;
    }

    /* DataTables sayfalama düğmelerini düzenle */
     .dataTables_wrapper .dataTables_paginate {
        float: left;
        margin-top: 10px;
    }

    /* Arama kutusunu düzenle */
    .dataTables_wrapper .dataTables_filter {
         float: right;
         margin-top: 10px; 
        background-color: #FFFFFF;
        margin: 10px, 10px, 10px, 10px;

    }
</style>

LibaryApp/Views/BorrowerBooks/AddBorrowerBook.cshtml
@model LibaryApp.Entity.Dtos.BorrowerBookDtos.AddBorrowerBooksDto
@{
    ViewBag.Title = "AddBorrowerBook";
}
<hr />
<div class="giris">
    <div class="form">
         <form class="giris-from" method="post" enctype="multipart/form-data">
               <b>Kitap Ödünç Verme Sayfası</b>
         
                <hr />
                <br />
        <div class="">
            <input type="text" placeholder="Ödünç Alan" name="BorrowersName"value="@Model.BorrowersName" />
             <label type="text" style="color:red">  @Html.ValidationMessageFor(x=>x.BorrowersName) </label>
             <br />
            <input type="text"  placeholder="Kitap Id" name="BookId"  value="@Model.BookId" readonly/>

            <input type="text" class="form-control-file" name="ReturnDate"  placeholder="Geri Getirme Tarihi" />
                @Html.ValidationMessageFor(model => model.ReturnDate)

            <label type="text" style="color:red">  @Html.ValidationMessageFor(x=>x.ReturnDate) </label>

        </div>
        <div style="margin-top:15px">
            <button type="submit" class="btn btn-info">Ödünç Ver</button>
        </div>
    </form>
    </div>

</div>
<style>

.giris {
    width: 360px;
    padding: 1% 0 0;
    margin-left: 330px;
    margin-top: -26px;
}

.form {
    position: relative;
    z-index: 1;
    background: #FFFFFF;
    max-width: 360px;
    margin: 0 auto 100px;
    padding: 45px;
    text-align: center;
    box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}

    .form input {
        font-family: "Roboto", sans-serif;
        outline: 0;
        background: #f2f2f2;
        width: 100%;
        border: 0;
        margin: 0 0 15px;
        padding: 15px;
        box-sizing: border-box;
        font-size: 14px;
    }

    .form button {
        font-family: "Roboto", sans-serif;
        text-transform: uppercase;
        outline: 0;
        background: royalblue;
        width: 100%;
        border: 0;
        padding: 15px;
        color: #FFFFFF;
        font-size: 14px;
        -webkit-transition: all 0.3 ease;
        transition: all 0.3 ease;
        cursor: pointer;
    }

        .form button:hover, .form button:active, .form button:focus {
            background: slateblue
        }

.container {
    position: relative;
    z-index: 1;
    max-width: 300px;
    margin: 0 auto;
}

LibaryApp/Views/BorrowerBooks/GetBorrowerBooksList.cshtml
@using LibaryApp.Entity.Dtos.BorrowerBookDtos
@model List<ListBorrowerBooksDto>
@{
    ViewData["Title"] = "GetBorrowerBooksList";
    Layout = "~/Views/Shared/_LayoutTemplate.cshtml";
}

<div class="container-fluid">
    <!-- DataTales-->
    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>

                        <tr>

                            <th class="book-info"></th>
                            <th class="book-info">Kitap</th>
                            <th class="book-info">Ödünç Alan</th>
                            <th class="book-info">Geri Getireceği Tarih</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var books in Model)
                        {
                            <tr>
                                <td style="text-align: center; vertical-align: middle">@books.Number</td>
                                
                                <td style="text-align: center; vertical-align: middle">@books.BookName</td>
                                <td style="text-align: center; vertical-align: middle;">@books.BorrowersName</td>
                                <td style="text-align: center; vertical-align: middle">@books.ReturnDate</td>
                            </tr>
                        }


                    </tbody>
                </table>


                <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
                <script src=" https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
                <script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap4.min.js"></script>
                <script src=" https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css"></script>

                <script src="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap4.min.css"></script>
                <script type="text/javascript">
                    var js = jQuery.noConflict(true);
                    js(document).ready(function () {
                        js('#dataTable').DataTable({
                            language: {
                                url: '//cdn.datatables.net/plug-ins/1.13.6/i18n/tr.json',
                            },

                        });
                    });
                </script>

            </div>
        </div>
    </div>


</div>

<style>

    th {
        vertical-align: middle;
        text-align: center;
    }

    .disabled-button {
        pointer-events: none; /* Butona tıklama olaylarını devre dışı bırakır */
        opacity: 0.6; /* Butonun opaklığını azaltır, tıklanamaz gibi görünmesini sağlar */
    }

    .borrow-btn {
        margin-top: 30px;
        margin-left: 5%;
        margin-right: 5%;
    }

    /* DataTables sayfalama düğmelerini düzenle */
    .dataTables_wrapper .dataTables_paginate {
        float: left;
        margin-top: 10px;
    }

    /* Arama kutusunu düzenle */
    .dataTables_wrapper .dataTables_filter {
        float: right;
        margin-top: 10px;
        background-color: #FFFFFF;
        margin: 10px, 10px, 10px, 10px;
    }
</style>

LibaryApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Handle</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>Mark</td>
            <td>Otto</td>
            <td>mdo</td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>fat</td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td>Larry</td>
            <td>the Bird</td>
            <td>twitter</td>
        </tr>
    </tbody>
</table>

<table class="table">
    <thead class="thead-light">
        <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Handle</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>Mark</td>
            <td>Otto</td>
            <td>mdo</td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>fat</td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td>Larry</td>
            <td>the Bird</td>
            <td>twitter</td>
        </tr>
    </tbody>
</table>

LibaryApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibaryApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibaryApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Book" asp-action="GetAll">LibaryApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="GetAll">Kitaplar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BorrowerBooks" asp-action="GetBorrowerBooksList">Dışarıdaki Kitaplar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LibaryApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>